// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lab_integrador.Data;

#nullable disable

namespace lab_integrador.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("lab_integrador.Models.ManufacturingProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ManufacturingProcesses");
                });

            modelBuilder.Entity("lab_integrador.Models.OrderProcess", b =>
                {
                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManufacturingProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductionOrderId", "ManufacturingProcessId");

                    b.HasIndex("ManufacturingProcessId");

                    b.ToTable("OrderProcesses");
                });

            modelBuilder.Entity("lab_integrador.Models.ProductionOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProductionOrders");
                });

            modelBuilder.Entity("lab_integrador.Models.OrderProcess", b =>
                {
                    b.HasOne("lab_integrador.Models.ManufacturingProcess", "ManufacturingProcess")
                        .WithMany("OrderProcesses")
                        .HasForeignKey("ManufacturingProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lab_integrador.Models.ProductionOrder", "ProductionOrder")
                        .WithMany("OrderProcesses")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManufacturingProcess");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("lab_integrador.Models.ManufacturingProcess", b =>
                {
                    b.Navigation("OrderProcesses");
                });

            modelBuilder.Entity("lab_integrador.Models.ProductionOrder", b =>
                {
                    b.Navigation("OrderProcesses");
                });
#pragma warning restore 612, 618
        }
    }
}
